CREATE TABLE pacientes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(20),
    cpf VARCHAR2(14) NOT NULL,

    -- Se "endereco" for um objeto composto, como uma classe com vários campos,
    -- você precisará criar colunas específicas para cada campo dele.
    logradouro VARCHAR2(100),
    bairro VARCHAR2(100),
    cep VARCHAR2(10),
    cidade VARCHAR2(100),
    uf VARCHAR2(2),
    complemento VARCHAR2(100),
    numero VARCHAR2(10)
);